### PR TITLE
platform.system() could return a value of Java causing the adb look up to fail on a windows system.

### PR DESCRIPTION
**Pull request by washyu**
Needed to do and extra check if platform.system() returns the value of 'Java' and check and the OS environment variable to see if we are in a Windows environment.  The os.getenv() will default to none if it not set.

### CODE REVIEW

**Comment by dtmilano** [comment]
Can you please tell me more about the case where you need 'Java' as the OS?

**Comment by washyu** [comment]
When I am testing my automation from the Eclipse IDE since it is running with JAVA any debug run will also be in this same JAVA environment hence the OS will be reported as JAVA.

**Comment by dtmilano** [comment]
Are you using PyDev?

On Wed, Mar 25, 2015 at 9:26 AM, washyu <notifications@github.com> wrote:

> When I am testing my automation from the Eclipse IDE since it is running
> with JAVA any debug run will also be in this same JAVA environment hence
> the OS will be reported as JAVA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/pull/138#issuecomment-86022524>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by washyu** [comment]
Sorry I was going to mention that.  Yes I am using pydev.


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Pull request merged**
