### PR TITLE
Feature/py3 upgrade

### PR DESCRIPTION
**Pull request by juliomfreitas**
Hello!

My company are planning to use this beautiful automation tool, but we uses python 3.6. So we are commited to have a py3 version of this lib.

Basicly we use the following stractegy in this PR:

* Firstly, revive the suite test case, fixing a namespace issue to give foundation of the entire job
* Pass the 2to3 utility in the entire code base to convert the raw
* make the tests pass the test suite **this is not complete! more latter in this doc**

I'm not usually take part on contibution of free software projects, so any suggestion will be well accepted.

Thanks and congratulations to the amazing job!

### CODE REVIEW

**Comment by juliomfreitas** [comment]
Here, on executing unittests:

`testContainsPoint_api15 (comm.dtmilano.android.viewclienttests.ViewTest) ... ok
testContainsPoint_api17 (comm.dtmilano.android.viewclienttests.ViewTest) ... ok
testCopyConstructor (comm.dtmilano.android.viewclienttests.ViewTest) ... ok
testGetClass (comm.dtmilano.android.viewclienttests.ViewTest) ... ok

[......]

testFindViewWithText_regexRoot (comm.dtmilano.android.viewclienttests.ViewClientTest) ... ok
testFindViewWithText_root (comm.dtmilano.android.viewclienttests.ViewClientTest) ... ok
testFindViewsContainingPoint_api15 (comm.dtmilano.android.viewclienttests.ViewClientTest) ... Alarm clock
`

It seems that the unittest quit for some reason I do not understand. Do you lived something like that?

Thanks,

**Comment by HDimka** [comment]
@dtmilano Hello, could you please the PR above? we also need this lib with py3

**Comment by dtmilano** [comment]
I totally agree that migration should happen, however, a lot of testing would be required. Some time ago I tried some automatic migration but a lot of manual work is still needed.

**Comment by dtmilano** [comment]
@juliomfreitas I'll see if I can find the problem with the tests. Thanks for your effort.

**Comment by juliomfreitas** [comment]
Just another point about the issue, the test suite did not work before the very start of the migration, and the error is pretty unfamiliar for me, I never see similar error, so I stucked on this

**Comment by dtmilano** [comment]
I created `py2to3` branch to use while we do the migration

**Comment by dtmilano** [comment]
28c7dc1c5c56dae021b9a00100f3b24a2fc46726 makes `dump` work but there's still a lot of work ahead to migrate all the functionality to python 3.

**Comment by juliomfreitas** [comment]
@dtmilano do you look over the test suite, if it is working?

**Comment by dtmilano** [comment]
Python 3 support is now in *master*.
Has been pre-released as **version 20.x.ybn** on Pypi and should work on both python 2.7 and 3.x.
It also introduces a more powerful backend: https://github.com/dtmilano/CulebraTester2-public

Enjoy, file bugs and contribute! :-)

**Pull request merged**
